google_plus:
  client_id: "234253985434-ugi0ie28jjrv7feek1k9hvo6h65eraqr.apps.googleusercontent.com"
  client_secret: "mChf8HC5OmbVPwwERKsS8QT9"
  redirect_uris: ["postmessage"]
  auth_uri: "https://accounts.google.com/o/oauth2/auth"
  token_uri: "https://accounts.google.com/o/oauth2/token"
