source 'https://rubygems.org'

gem 'rails', '3.2.19'

gem 'google-api-client', '>= 0.6.2', require: 'google/api_client'
gem 'signet', '>=0.4.5'
gem 'json', '1.8.1'

group :development, :test do
  gem 'rake'
  gem 'pry'
  gem 'rspec-rails', '~>3.0.0'
  gem 'simplecov', require: false
end

group :development do
  gem 'sqlite3'
end

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end

